export const predefinedDomains = [
  "Accesorii baie",
  "Accesorii Computer",
  "Acoperișuri – Comercial",
  "Acoperișuri – Rezidențial",
  "Activități Angajare (altele)",
  "Acupunctură",
  "Acvarii/Pesti",
  "Administrarea consorțiilor",
  "Administrarea proprietăților comerciale",
  "Administrator apartamente",
  "Administrator financiar",
  "Agent achizții",
  "Agent imobiliar rezidential",
  "Agent turism",
  "Agenție publicitate",
  "Agenție recrutare",
  "Agricultură (altele)",
  "Agronom",
  "AI Consultant",
  "Amenajări peisagistice cu elemente dure",
  "Angajarea lucrătorilor străini",
  "Animale (altele)",
  "Antrenor",
  "Antrenor Personal - Fitness",
  "Antrenor Yoga/Pilates/Qi-gong",
  "Arhitect",
  "Arhitect comercial",
  "Arhitect gradini si peisaje",
  "Arhitectura de interior",
  "Arhitectură & Inginerie (altele)",
  "Arhitectură Vaastu",
  "Arte & Distracție (altele)",
  "Arte marțiale",
  "Artist",
  "Ascensoare",
  "Asigurare proprietăți",
  "Asigurari suplimentare",
  "Asigurari vehicule",
  "Asigurări comerciale",
  "Asigurări sănătate",
  "Asigurări viață și disabilitate",
  "Asistent virtual",
  "Astrolog",
  "Auditor",
  "Auto & Moto (altele)",
  "Automatizari industriale",
  "Automatizări case",
  "Auz/Audiologie",
  "Avocat - infiintari, modificari societati",
  "Avocat insolventa",
  "Avocatura - Drept comercial",
  "Avocatură - Drept civil",
  "Avocatură - drept penal",
  "Avocatură - Dreptul muncii",
  "Avocatură - probleme imobiliare",
  "Avocatură - probleme persoane vârstnice",
  "Avocatură dreptul familiei",
  "Avocatură imigrări",
  "Avocatură imobiliară",
  "Avocatură probleme sănătate",
  "Avocatură proprietate intelectuala",
  "Avocatură taxe",
  "Avocatură vătămare corporală",
  "Balcoane/Verande",
  "Banker personal",
  "Barter & criptomonede",
  "Bauturi",
  "Beneficii de grup",
  "Benzinărie",
  "Bijuterii",
  "Bijuterii fine",
  "Blaturi/suprafete de lucru",
  "Boats",
  "Branding",
  "Broker actiuni",
  "Broker afaceri",
  "Broker asigurari",
  "Brutar",
  "Cafenea",
  "Call Center",
  "Camere de comerț/Asociații",
  "Canalizare",
  "Cartuse/Produse tiparire",
  "Catering",
  "Cauciuc & Plastic",
  "CCTV",
  "Centru de divertisment",
  "Centru educațional",
  "Centru formare",
  "Centru sănătate/Gym/Club",
  "Chiropractor",
  "Chocolatier",
  "Ciment/Beton",
  "Coach Comunicare",
  "Coach financiar",
  "Coach Leadership",
  "Coach management",
  "Coach parenting",
  "Coach pentru dezvoltare mentală",
  "Coach relații",
  "Coach viata",
  "Coach vocal",
  "Coach Wellness",
  "Colecții",
  "Combustibili",
  "Comert ceai",
  "Comert Electrocasnice",
  "Comert international",
  "Comert Materiale construcții",
  "Comert podele",
  "Comert usi",
  "Comert vopsea",
  "Companie mutări",
  "Companie sisteme semnalizare",
  "Computer, Electronice & Optica",
  "Computere & Programare (altele)",
  "Consilier/Psihoterapeut",
  "Constructii/Piatră",
  "Constructor case",
  "Constructor de case pe comandă",
  "Constructor șeminee & cuptoare",
  "Construcții (altele)",
  "Construcții bucătărie",
  "Construcții comerciale",
  "Construcții/Contractare generală",
  "Consultant afaceri",
  "Consultant asigurari",
  "Consultant business",
  "Consultant business - Afaceri mici",
  "Consultant business - Managementul calității",
  "Consultant business - Organizare & Procese",
  "Consultant business - Reorganizare",
  "Consultant business- Management",
  "Consultant Culoare & Stil",
  "Consultant financiar",
  "Consultant IT",
  "Consultant legislatia muncii",
  "Consultant Marketing",
  "Consultant planificari imobiliare",
  "Consultant taxe",
  "Consultant Vaastu",
  "Consultant viză",
  "Consultanta - energie",
  "Consultanță (altele)",
  "Consultanță în educație",
  "Contabil autorizat",
  "Contabilitate primară",
  "Content digital",
  "Contractor civil",
  "Contractor demolare",
  "Contractor general",
  "Copywriter/Scriitor",
  "Cosmetica animale",
  "Cosmetice/Îngrijire piele",
  "Covoare",
  "Creare companii offshore",
  "Credit Card/Servicii furnizori",
  "Croitorie/haine la comandă",
  "Curatare ferestre",
  "Curatenie comerciala",
  "Curățătorie covoare/tapițerie",
  "Curățătorie/spalatorie",
  "Curățenie - Exterior",
  "Curățenie - Rezidențială",
  "Curățenie ventilații",
  "Curățenie- Piscina, Spa & Saună",
  "Curier",
  "Cursuri",
  "Cursuri de limbi străine",
  "Daruind vei dobandi®",
  "Daruri",
  "Dermatologist",
  "Design interior",
  "Design Interior  - Comercial",
  "Designer grafic",
  "Detailing auto",
  "Detectiv/Servicii investigații",
  "Dezinsecție – Comercial",
  "Dezinsecție – Rezidențial",
  "Dezinsecție – Țânțari",
  "Dezvoltare imobiliara",
  "Dezvoltator Aplicatii",
  "Diamante",
  "Disc Jockey (DJ)",
  "Distracție",
  "Distribuitor bauturi",
  "Distribuitor ceai",
  "Distribuție cafea",
  "Diversitate, Egalitate si Incluziune",
  "Doctor",
  "Drept administrativ",
  "Drept corporativ",
  "Drept pensii",
  "Dreptul consumatorului",
  "Dresor caini",
  "Dulciuri",
  "Echipament transport",
  "Echipamente birou",
  "Echipamente electrice",
  "Echipamente și consumabile pentru curățenie",
  "Editura",
  "Electrician",
  "Electrician - Commercial",
  "Electricitate & Gaz",
  "ERP Software",
  "Estetician",
  "Evaluări imobiliare",
  "Evenimente",
  "Evenimente & Servicii afaceri (altele)",
  "Evenimente Corporate",
  "Expert Auto",
  "Farmacie",
  "Farmacist",
  "Feng Shui",
  "Ferestre & Uși",
  "Ferestre și uși din uPVC",
  "Fierar",
  "Finanțare Business",
  "Finanțe & Asigurări (altele)",
  "Florărie",
  "Fonduri mutuale",
  "Fotograf",
  "Fotograf - Comercial",
  "Furnizor / Distribuitor de placaj",
  "Furnizor de hardware IT",
  "Furnizor de legume",
  "Furnizor servicii pentru vârstnici",
  "Furnizori lemn",
  "Garantii imobiliare",
  "Garduri",
  "Generare lead-uri",
  "Generatore curent",
  "Ghid turism",
  "Ginecologist",
  "Golf",
  "Hair Stylist",
  "Hartie & Produse din hartie",
  "Hipnoterapeut",
  "Hospice",
  "Hotel",
  "Hotel animale",
  "HVAC - Încălzire & Aer",
  "Imobiliare comerciale",
  "Impachetare",
  "Imprumuturi",
  "Imprumuturi companii",
  "Imprumuturi imobiliare",
  "Inchiriere echipamente",
  "Inchiriere evenimente",
  "Inchiriere spații de depozitare",
  "Inchirieri imobiliare",
  "Inchirieri/Vânzări/Leasing auto",
  "Inființare Companii",
  "Infusion Spa",
  "Inginer încălzire",
  "Inginerie",
  "Ingrijire gazon",
  "Inot",
  "Inspector imobiliar",
  "Inspecții case",
  "Instalatii Aluminium",
  "Instalator",
  "Instalații IT",
  "Instructor auto",
  "Instructor Golf",
  "Instruire lingvistică",
  "Integrare software",
  "Investitii financiare",
  "Investiții imobiliare",
  "Ipoteci imobiliare",
  "Ipoteci rezidențiale",
  "Irigatie",
  "IT & Rețele",
  "IT Hardware",
  "Izolație",
  "Îmbrăcăminte pentru femei",
  "Închiriere containere",
  "Închiriere locație/cameră evenimente",
  "Îndepărtare buruieni",
  "Îngrijire la domiciliu",
  "Întreținere și curățare coșuri de fum",
  "Jaluzele & Copertine",
  "Juridic & Contabilitate (altele)",
  "Laboratoare clinice",
  "Lacatuș",
  "Lemn & Pluta (exclusiv mobila)",
  "Lucrari teren",
  "Lumanari",
  "Makeup Artist",
  "Management avere",
  "Management gunoi",
  "Managementul greutății",
  "Managementul proprietății",
  "Manager evenimente",
  "Mancare pentru animale de companie",
  "Manufactura masinarii & echipament",
  "Manufactura metal",
  "Marketing Digital",
  "Marketing online",
  "Marketing Relații",
  "Materiale acoperire pereti",
  "Mâncare & Băuturi (altele)",
  "Media",
  "Mediator",
  "Medical Spa",
  "Medicare",
  "Medicină alternativă",
  "Mentenanță proprietăți imobiliare",
  "Meseriaș",
  "Metale",
  "Minerale nemetalice",
  "Mobilare case",
  "Mobilă",
  "Mobilă birouri",
  "Modelare 3D",
  "Modificari Asigurari",
  "Muncitor faianță/gresie",
  "Muzician",
  "Naturopat",
  "Notar",
  "Nutriționist",
  "Ofertare",
  "Oficiant",
  "Oftalmologie",
  "Optical Products",
  "Optimizare motor cautare (SEO)",
  "Organizator profesionist",
  "Organizații & Altele (altele)",
  "Organizații non-profit",
  "Ortodont",
  "Osteopat",
  "Oțelarie",
  "Panouri publicitare exterioare",
  "Parbrize",
  "Parfum",
  "Pensii",
  "Perdele/Jaluzele",
  "Pet Shop",
  "Pictor - Comercial",
  "Pictor - Rezidential",
  "Piese&accesorii auto",
  "Piscine, Spa & Sauna",
  "Placi ceramice",
  "Planificare evenimente",
  "Planificator nunti",
  "Podcasturi",
  "Podele",
  "Podiatrist",
  "Polițist",
  "Portal și furnizare de conținut",
  "Practician insolventa",
  "Pregătire case",
  "Print serigrafic",
  "Producător film",
  "Productie",
  "Productie (altele)",
  "Productie echipamente electrice",
  "Productie mobila",
  "Productie vopsea",
  "Productii",
  "Producție de energie electrică",
  "Producție vehicule utilitare",
  "Produse alimentare",
  "Produse chimice",
  "Produse curățenie",
  "Produse Health & Wellness",
  "Produse mediu",
  "Produse Petroliere",
  "Produse piele",
  "Produse promoționale",
  "Produse tutun",
  "Produse/Servicii Telecomunicații",
  "Profesionist BNI",
  "Programator",
  "Proiectant clădiri",
  "Project Management Constructii",
  "Promovare vânzări",
  "Proprietar galerie de artă",
  "Protectie apa/intemperii",
  "Protecția muncii",
  "Protecție incendii",
  "Publicitate & Marketing (altele)",
  "Publicitate Radio",
  "Publicitate tipărită",
  "Publicitate TV",
  "Rechizite",
  "Recrutor",
  "Redresare Credit",
  "Relații publice",
  "Reparatii camioane",
  "Reparatii masinarii & echipament",
  "Reparații (altele)",
  "Reparații auto",
  "Reparații bijuterii",
  "Reparații computer",
  "Reparații electrocasnice",
  "Reparații mobilă/tapițerie",
  "Reparații piscine, spa și saun",
  "Responsabil Protectia Datelor",
  "Restaurant",
  "Restaurări",
  "Resurse umane",
  "Retail (altele)",
  "Retail haine & accesorii",
  "Rigips",
  "Salon/Spa",
  "Saltele",
  "Sănătate & Wellness (altele)",
  "Schimb valutar",
  "Scutiri taxe Imobiliare",
  "Secretariat",
  "Securitate (altele)",
  "Securitate date",
  "Securitatea angajaților",
  "Service auto",
  "Servicii ACP",
  "Servicii administrative",
  "Servicii arhitecturale",
  "Servicii asfaltare",
  "Servicii bancare",
  "Servicii bancare comerciale",
  "Servicii băuturi",
  "Servicii birouri",
  "Servicii Cloud",
  "Servicii contabilitate",
  "Servicii copaci",
  "Servicii de bar mobil",
  "Servicii de capturare și relocare animale sălbatice",
  "Servicii de colectare a deșeurilor",
  "Servicii de concierge medical",
  "Servicii de creditare",
  "Servicii de Iluminare",
  "Servicii de prelucrare CNC",
  "Servicii de renovare – Comercial",
  "Servicii de renovare – Rezidențial",
  "Servicii de securitate cibernetică",
  "Servicii E-Commerce",
  "Servicii educație",
  "Servicii energie",
  "Servicii funerare",
  "Servicii guvernamentale",
  "Servicii Health & Wellness",
  "Servicii imobiliare (altele)",
  "Servicii internet",
  "Servicii ipoteci, acte proprietate",
  "Servicii juridice",
  "Servicii magazin online",
  "Servicii mâncare",
  "Servicii Media",
  "Servicii medicale",
  "Servicii mediu",
  "Servicii naveta/limuzine",
  "Servicii peisagistică",
  "Servicii personale (altele)",
  "Servicii salarizare",
  "Servicii tipărire",
  "Servicii traduceri",
  "Servicii transport bunuri",
  "Sistem de colectare a apelor pluviale",
  "Sisteme Apa",
  "Sisteme GPS / Navigație prin satelit",
  "Sisteme home cinema",
  "Sisteme securitate",
  "Sisteme septice",
  "Social Media",
  "Sofrolog",
  "Software calculatoare",
  "Solar",
  "Spalatorie/Curatare masini",
  "Spațiu Coworking",
  "Spălat",
  "Sport&Timp liber (altele)",
  "Sticlă",
  "Stomatologie",
  "Straturi protectoare/sigilatoare",
  "Structuri temporare muncitori",
  "Supermarket",
  "Suplimente nutriționale",
  "Supraveghetor",
  "Supraveghetor cantitate",
  "Tamplar",
  "Tavan fals / Tavan suspendat",
  "Tehnician - Audio,Video",
  "Telecomunicații (altele)",
  "Telecomunicații mobile",
  "Tencuitor",
  "Terapeut masaj",
  "Terapeut recuperare fizică",
  "Testamente/Fonduri",
  "Textile",
  "Tipograf -  Format mare",
  "Tipograf - Digital",
  "Tipograf - Offset",
  "Tocarea hârtiei / documentelor",
  "Tractare vehicule",
  "Training & Coaching (altele)",
  "Training IT",
  "Training online",
  "Training/Coach business",
  "Training/Coach Vanzari",
  "Transfer drept de proprietate",
  "Transport & Expeditii (altele)",
  "Transport comercial",
  "Tratament Ferestre",
  "Trimiteri poștă",
  "Turism (altele)",
  "Țevi",
  "Uleiuri esențiale",
  "Uniforme",
  "UPS",
  "Usi garaj",
  "Vanzare materiale contructii",
  "Vânzare bilete",
  "Vânzare cărți",
  "Vânzare computer",
  "Vânzare de mașini second-hand",
  "Vânzare electronice",
  "Vânzare mobilă",
  "Vânzare vehicule comerciale",
  "Vânzări auto",
  "Vânzări de proprietăți",
  "Vânzări produse sport",
  "Vânzări sisteme iluminat",
  "Vânzări/montaj anvelope",
  "Vehicule motorizate",
  "Veterinar",
  "Vin/Furnizori vin",
  "Web Design",
  "Web Development"
] as const
