// EN→RO mapping for BNI Connect classifications. BNI API returns English; our list is Romanian.
// ponytail: generated from BNI standard classification list. Add entries as new mismatches surface.
export const domainEnToRo: Record<string, string> = {
  'Bathroom accessories': 'Accesorii baie',
  'Computer accessories': 'Accesorii Computer',
  'Roofing - Commercial': 'Acoperișuri – Comercial',
  'Roofing - Residential': 'Acoperișuri – Rezidențial',
  'Employment activities (other)': 'Activități Angajare (altele)',
  'Acupuncture': 'Acupunctură',
  'Aquariums/Fish': 'Acvarii/Pesti',
  'Condominium management': 'Administrarea consorțiilor',
  'Commercial property management': 'Administrarea proprietăților comerciale',
  'Apartment manager': 'Administrator apartamente',
  'Financial administrator': 'Administrator financiar',
  'Purchasing agent': 'Agent achizții',
  'Residential real estate agent': 'Agent imobiliar rezidential',
  'Travel agent': 'Agent turism',
  'Advertising agency': 'Agenție publicitate',
  'Recruitment agency': 'Agenție recrutare',
  'Agriculture (other)': 'Agricultură (altele)',
  'Agronomist': 'Agronom',
  'AI Consultant': 'AI Consultant',
  'Hardscaping': 'Amenajări peisagistice cu elemente dure',
  'Foreign worker hiring': 'Angajarea lucrătorilor străini',
  'Animals (other)': 'Animale (altele)',
  'Coach': 'Antrenor',
  'Personal trainer - Fitness': 'Antrenor Personal - Fitness',
  'Yoga/Pilates/Qi-gong trainer': 'Antrenor Yoga/Pilates/Qi-gong',
  'Architect': 'Arhitect',
  'Commercial architect': 'Arhitect comercial',
  'Garden and landscape architect': 'Arhitect gradini si peisaje',
  'Interior architecture': 'Arhitectura de interior',
  'Architecture & Engineering (other)': 'Arhitectură & Inginerie (altele)',
  'Vaastu architecture': 'Arhitectură Vaastu',
  'Arts & Entertainment (other)': 'Arte & Distracție (altele)',
  'Martial arts': 'Arte marțiale',
  'Artist': 'Artist',
  'Elevators': 'Ascensoare',
  'Property insurance': 'Asigurare proprietăți',
  'Supplemental insurance': 'Asigurari suplimentare',
  'Vehicle insurance': 'Asigurari vehicule',
  'Commercial insurance': 'Asigurări comerciale',
  'Health insurance': 'Asigurări sănătate',
  'Life and disability insurance': 'Asigurări viață și disabilitate',
  'Virtual assistant': 'Asistent virtual',
  'Astrologer': 'Astrolog',
  'Auditor': 'Auditor',
  'Auto & Moto (other)': 'Auto & Moto (altele)',
  'Industrial automation': 'Automatizari industriale',
  'Home automation': 'Automatizări case',
  'Hearing/Audiology': 'Auz/Audiologie',
  'Lawyer - company formation': 'Avocat - infiintari, modificari societati',
  'Insolvency lawyer': 'Avocat insolventa',
  'Business law': 'Avocatura - Drept comercial',
  'Civil law': 'Avocatură - Drept civil',
  'Criminal law': 'Avocatură - drept penal',
  'Employment law': 'Avocatură - Dreptul muncii',
  'Real estate law': 'Avocatură - probleme imobiliare',
  'Elder law': 'Avocatură - probleme persoane vârstnice',
  'Family law': 'Avocatură dreptul familiei',
  'Immigration law': 'Avocatură imigrări',
  'Real estate attorney': 'Avocatură imobiliară',
  'Health law': 'Avocatură probleme sănătate',
  'Intellectual property law': 'Avocatură proprietate intelectuala',
  'Tax law': 'Avocatură taxe',
  'Personal injury law': 'Avocatură vătămare corporală',
  'Balconies/Verandas': 'Balcoane/Verande',
  'Personal banker': 'Banker personal',
  'Barter & Cryptocurrency': 'Barter & criptomonede',
  'Beverages': 'Bauturi',
  'Group benefits': 'Beneficii de grup',
  'Gas station': 'Benzinărie',
  'Jewelry': 'Bijuterii',
  'Fine jewelry': 'Bijuterii fine',
  'Countertops': 'Blaturi/suprafete de lucru',
  'Boats': 'Boats',
  'Branding': 'Branding',
  'Stock broker': 'Broker actiuni',
  'Business broker': 'Broker afaceri',
  'Insurance broker': 'Broker asigurari',
  'Baker': 'Brutar',
  'Cafe': 'Cafenea',
  'Call Center': 'Call Center',
  'Chambers of commerce/Associations': 'Camere de comerț/Asociații',
  'Drainage': 'Canalizare',
  'Cartridges/Printing products': 'Cartuse/Produse tiparire',
  'Catering': 'Catering',
  'Rubber & Plastic': 'Cauciuc & Plastic',
  'CCTV': 'CCTV',
  'Entertainment center': 'Centru de divertisment',
  'Educational center': 'Centru educațional',
  'Training center': 'Centru formare',
  'Health center/Gym/Club': 'Centru sănătate/Gym/Club',
  'Chiropractor': 'Chiropractor',
  'Chocolatier': 'Chocolatier',
  'Cement/Concrete': 'Ciment/Beton',
  'Communication coach': 'Coach Comunicare',
  'Financial coach': 'Coach financiar',
  'Leadership coach': 'Coach Leadership',
  'Management coach': 'Coach management',
  'Parenting coach': 'Coach parenting',
  'Mental development coach': 'Coach pentru dezvoltare mentală',
  'Relationship coach': 'Coach relații',
  'Life coach': 'Coach viata',
  'Vocal coach': 'Coach vocal',
  'Wellness coach': 'Coach Wellness',
  'Collections': 'Colecții',
  'Fuels': 'Combustibili',
  'Tea trade': 'Comert ceai',
  'Appliance trade': 'Comert Electrocasnice',
  'International trade': 'Comert international',
  'Building materials trade': 'Comert Materiale construcții',
  'Flooring trade': 'Comert podele',
  'Door trade': 'Comert usi',
  'Paint trade': 'Comert vopsea',
  'Moving company': 'Companie mutări',
  'Signage company': 'Companie sisteme semnalizare',
  'Computer, Electronics & Optics': 'Computer, Electronice & Optica',
  'Computers & Programming (other)': 'Computere & Programare (altele)',
  'Counselor/Psychotherapist': 'Consilier/Psihoterapeut',
  'Masonry': 'Constructii/Piatră',
  'Home builder': 'Constructor case',
  'Custom home builder': 'Constructor de case pe comandă',
  'Fireplace & oven builder': 'Constructor șeminee & cuptoare',
  'Construction (other)': 'Construcții (altele)',
  'Kitchen construction': 'Construcții bucătărie',
  'Commercial construction': 'Construcții comerciale',
  'General contracting': 'Construcții/Contractare generală',
  'Business consultant': 'Consultant afaceri',
  'Insurance consultant': 'Consultant asigurari',
  'Business consultant (general)': 'Consultant business',
  'Business consultant - Small business': 'Consultant business - Afaceri mici',
  'Business consultant - Quality management': 'Consultant business - Managementul calității',
  'Business consultant - Organization & Processes': 'Consultant business - Organizare & Procese',
  'Business consultant - Reorganization': 'Consultant business - Reorganizare',
  'Business consultant - Management': 'Consultant business- Management',
  'Color & Style consultant': 'Consultant Culoare & Stil',
  'Financial consultant': 'Consultant financiar',
  'IT consultant': 'Consultant IT',
  'Employment law consultant': 'Consultant legislatia muncii',
  'Marketing consultant': 'Consultant Marketing',
  'Real estate planning consultant': 'Consultant planificari imobiliare',
  'Tax consultant': 'Consultant taxe',
  'Vaastu consultant': 'Consultant Vaastu',
  'Visa consultant': 'Consultant viză',
  'Energy consultant': 'Consultanta - energie',
  'Consulting (other)': 'Consultanță (altele)',
  'Education consulting': 'Consultanță în educație',
  'Certified accountant': 'Contabil autorizat',
  'Primary accounting': 'Contabilitate primară',
  'Digital content': 'Content digital',
  'Civil contractor': 'Contractor civil',
  'Demolition contractor': 'Contractor demolare',
  'General contractor': 'Contractor general',
  'Copywriter/Writer': 'Copywriter/Scriitor',
  'Pet grooming': 'Cosmetica animale',
  'Cosmetics/Skincare': 'Cosmetice/Îngrijire piele',
  'Carpets': 'Covoare',
  'Offshore company creation': 'Creare companii offshore',
  'Credit card/Merchant services': 'Credit Card/Servicii furnizori',
  'Tailoring/Custom clothing': 'Croitorie/haine la comandă',
  'Window cleaning': 'Curatare ferestre',
  'Commercial cleaning': 'Curatenie comerciala',
  'Carpet/Upholstery cleaning': 'Curățătorie covoare/tapițerie',
  'Dry cleaning/Laundry': 'Curățătorie/spalatorie',
  'Exterior cleaning': 'Curățenie - Exterior',
  'Residential cleaning': 'Curățenie - Rezidențială',
  'Ventilation cleaning': 'Curățenie ventilații',
  'Pool, Spa & Sauna cleaning': 'Curățenie- Piscina, Spa & Saună',
  'Courier': 'Curier',
  'Courses': 'Cursuri',
  'Foreign language courses': 'Cursuri de limbi străine',
  'Givers gain': 'Daruind vei dobandi®',
  'Gifts': 'Daruri',
  'Dermatologist': 'Dermatologist',
  'Interior design': 'Design interior',
  'Interior design - Commercial': 'Design Interior  - Comercial',
  'Graphic designer': 'Designer grafic',
  'Auto detailing': 'Detailing auto',
  'Detective/Investigation services': 'Detectiv/Servicii investigații',
  'Pest control - Commercial': 'Dezinsecție – Comercial',
  'Pest control - Residential': 'Dezinsecție – Rezidențial',
  'Mosquito control': 'Dezinsecție – Țânțari',
  'Real estate development': 'Dezvoltare imobiliara',
  'App developer': 'Dezvoltator Aplicatii',
  'Diamonds': 'Diamante',
  'Disc Jockey (DJ)': 'Disc Jockey (DJ)',
  'Entertainment': 'Distracție',
  'Beverage distributor': 'Distribuitor bauturi',
  'Tea distributor': 'Distribuitor ceai',
  'Coffee distribution': 'Distribuție cafea',
  'Diversity, Equity and Inclusion': 'Diversitate, Egalitate si Incluziune',
  'Doctor': 'Doctor',
  'Administrative law': 'Drept administrativ',
  'Corporate law': 'Drept corporativ',
  'Pension law': 'Drept pensii',
  'Consumer law': 'Dreptul consumatorului',
  'Dog trainer': 'Dresor caini',
  'Sweets': 'Dulciuri',
  'Transport equipment': 'Echipament transport',
  'Office equipment': 'Echipamente birou',
  'Electrical equipment': 'Echipamente electrice',
  'Cleaning equipment and supplies': 'Echipamente și consumabile pentru curățenie',
  'Publishing house': 'Editura',
  'Electrician': 'Electrician',
  'Electrician - Commercial': 'Electrician - Commercial',
  'Electricity & Gas': 'Electricitate & Gaz',
  'ERP Software': 'ERP Software',
  'Aesthetician': 'Estetician',
  'Real estate appraisals': 'Evaluări imobiliare',
  'Events': 'Evenimente',
  'Events & Business services (other)': 'Evenimente & Servicii afaceri (altele)',
  'Corporate events': 'Evenimente Corporate',
  'Auto expert': 'Expert Auto',
  'Pharmacy': 'Farmacie',
  'Pharmacist': 'Farmacist',
  'Feng Shui': 'Feng Shui',
  'Windows & Doors': 'Ferestre & Uși',
  'uPVC windows and doors': 'Ferestre și uși din uPVC',
  'Blacksmith': 'Fierar',
  'Business financing': 'Finanțare Business',
  'Finance & Insurance (other)': 'Finanțe & Asigurări (altele)',
  'Florist': 'Florărie',
  'Mutual funds': 'Fonduri mutuale',
  'Photographer': 'Fotograf',
  'Photographer - Commercial': 'Fotograf - Comercial',
  'Plywood supplier': 'Furnizor / Distribuitor de placaj',
  'IT hardware supplier': 'Furnizor de hardware IT',
  'Vegetable supplier': 'Furnizor de legume',
  'Senior services provider': 'Furnizor servicii pentru vârstnici',
  'Timber suppliers': 'Furnizori lemn',
  'Real estate warranties': 'Garantii imobiliare',
  'Fencing': 'Garduri',
  'Lead generation': 'Generare lead-uri',
  'Power generators': 'Generatore curent',
  'Tour guide': 'Ghid turism',
  'Gynecologist': 'Ginecologist',
  'Golf': 'Golf',
  'Hair Stylist': 'Hair Stylist',
  'Paper & Paper products': 'Hartie & Produse din hartie',
  'Hypnotherapist': 'Hipnoterapeut',
  'Hospice': 'Hospice',
  'Hotel': 'Hotel',
  'Pet hotel': 'Hotel animale',
  'HVAC - Heating & Air': 'HVAC - Încălzire & Aer',
  'Commercial real estate': 'Imobiliare comerciale',
  'Packaging': 'Impachetare',
  'Loans': 'Imprumuturi',
  'Company loans': 'Imprumuturi companii',
  'Real estate loans': 'Imprumuturi imobiliare',
  'Equipment rental': 'Inchiriere echipamente',
  'Event rental': 'Inchiriere evenimente',
  'Storage space rental': 'Inchiriere spații de depozitare',
  'Real estate rental': 'Inchirieri imobiliare',
  'Auto rental/Sales/Leasing': 'Inchirieri/Vânzări/Leasing auto',
  'Company formation': 'Inființare Companii',
  'Infusion Spa': 'Infusion Spa',
  'Heating engineer': 'Inginer încălzire',
  'Engineering': 'Inginerie',
  'Lawn care': 'Ingrijire gazon',
  'Swimming': 'Inot',
  'Real estate inspector': 'Inspector imobiliar',
  'Home inspections': 'Inspecții case',
  'Aluminium installations': 'Instalatii Aluminium',
  'Plumber': 'Instalator',
  'IT installations': 'Instalații IT',
  'Driving instructor': 'Instructor auto',
  'Golf instructor': 'Instructor Golf',
  'Linguistic training': 'Instruire lingvistică',
  'Software integration': 'Integrare software',
  'Financial investments': 'Investitii financiare',
  'Real estate investments': 'Investiții imobiliare',
  'Residential mortgages': 'Ipoteci rezidențiale',
  'Irrigation': 'Irigatie',
  'IT & Networks': 'IT & Rețele',
  'IT Hardware': 'IT Hardware',
  'Insulation': 'Izolație',
  'Women\'s clothing': 'Îmbrăcăminte pentru femei',
  'Container rental': 'Închiriere containere',
  'Event venue rental': 'Închiriere locație/cameră evenimente',
  'Weed removal': 'Îndepărtare buruieni',
  'Home care': 'Îngrijire la domiciliu',
  'Chimney maintenance and cleaning': 'Întreținere și curățare coșuri de fum',
  'Blinds & Awnings': 'Jaluzele & Copertine',
  'Legal & Accounting (other)': 'Juridic & Contabilitate (altele)',
  'Clinical laboratories': 'Laboratoare clinice',
  'Locksmith': 'Lacatuș',
  'Wood & Cork': 'Lemn & Pluta (exclusiv mobila)',
  'Earthworks': 'Lucrari teren',
  'Candles': 'Lumanari',
  'Makeup Artist': 'Makeup Artist',
  'Wealth management': 'Management avere',
  'Waste management': 'Management gunoi',
  'Weight management': 'Managementul greutății',
  'Property management': 'Managementul proprietății',
  'Event manager': 'Manager evenimente',
  'Pet food': 'Mancare pentru animale de companie',
  'Machinery & Equipment manufacturing': 'Manufactura masinarii & echipament',
  'Metal manufacturing': 'Manufactura metal',
  'Digital marketing': 'Marketing Digital',
  'Online marketing': 'Marketing online',
  'Relationship marketing': 'Marketing Relații',
  'Wall covering materials': 'Materiale acoperire pereti',
  'Food & Beverages (other)': 'Mâncare & Băuturi (altele)',
  'Media': 'Media',
  'Mediator': 'Mediator',
  'Medical Spa': 'Medical Spa',
  'Medicare': 'Medicare',
  'Alternative medicine': 'Medicină alternativă',
  'Property maintenance': 'Mentenanță proprietăți imobiliare',
  'Handyman': 'Meseriaș',
  'Metals': 'Metale',
  'Non-metallic minerals': 'Minerale nemetalice',
  'Home furnishing': 'Mobilare case',
  'Furniture': 'Mobilă',
  'Office furniture': 'Mobilă birouri',
  '3D Modeling': 'Modelare 3D',
  'Insurance modifications': 'Modificari Asigurari',
  'Tile worker': 'Muncitor faianță/gresie',
  'Musician': 'Muzician',
  'Naturopath': 'Naturopat',
  'Notary': 'Notar',
  'Nutritionist': 'Nutriționist',
  'Quoting': 'Ofertare',
  'Officiant': 'Oficiant',
  'Ophthalmology': 'Oftalmologie',
  'Optical Products': 'Optical Products',
  'SEO': 'Optimizare motor cautare (SEO)',
  'Professional organizer': 'Organizator profesionist',
  'Organizations & Other (other)': 'Organizații & Altele (altele)',
  'Non-profit organizations': 'Organizații non-profit',
  'Orthodontist': 'Ortodont',
  'Osteopath': 'Osteopat',
  'Steel mill': 'Oțelarie',
  'Outdoor advertising': 'Panouri publicitare exterioare',
  'Windshields': 'Parbrize',
  'Perfume': 'Parfum',
  'Pensions': 'Pensii',
  'Curtains/Blinds': 'Perdele/Jaluzele',
  'Pet Shop': 'Pet Shop',
  'Painter - Commercial': 'Pictor - Comercial',
  'Painter - Residential': 'Pictor - Rezidential',
  'Auto parts & accessories': 'Piese&accesorii auto',
  'Pools, Spa & Sauna': 'Piscine, Spa & Sauna',
  'Ceramic tiles': 'Placi ceramice',
  'Event planning': 'Planificare evenimente',
  'Wedding planner': 'Planificator nunti',
  'Podcasts': 'Podcasturi',
  'Flooring': 'Podele',
  'Podiatrist': 'Podiatrist',
  'Police officer': 'Polițist',
  'Content portal': 'Portal și furnizare de conținut',
  'Insolvency practitioner': 'Practician insolventa',
  'Home staging': 'Pregătire case',
  'Screen printing': 'Print serigrafic',
  'Film producer': 'Producător film',
  'Manufacturing': 'Productie',
  'Manufacturing (other)': 'Productie (altele)',
  'Electrical equipment manufacturing': 'Productie echipamente electrice',
  'Furniture manufacturing': 'Productie mobila',
  'Paint manufacturing': 'Productie vopsea',
  'Productions': 'Productii',
  'Electricity production': 'Producție de energie electrică',
  'Commercial vehicle production': 'Producție vehicule utilitare',
  'Food products': 'Produse alimentare',
  'Chemical products': 'Produse chimice',
  'Cleaning products': 'Produse curățenie',
  'Health & Wellness products': 'Produse Health & Wellness',
  'Environmental products': 'Produse mediu',
  'Petroleum products': 'Produse Petroliere',
  'Leather products': 'Produse piele',
  'Promotional products': 'Produse promoționale',
  'Tobacco products': 'Produse tutun',
  'Telecommunications products/services': 'Produse/Servicii Telecomunicații',
  'BNI Professional': 'Profesionist BNI',
  'Programmer': 'Programator',
  'Building designer': 'Proiectant clădiri',
  'Construction project management': 'Project Management Constructii',
  'Sales promotion': 'Promovare vânzări',
  'Art gallery owner': 'Proprietar galerie de artă',
  'Water/Weatherproofing': 'Protectie apa/intemperii',
  'Occupational safety': 'Protecția muncii',
  'Fire protection': 'Protecție incendii',
  'Advertising & Marketing (other)': 'Publicitate & Marketing (altele)',
  'Radio advertising': 'Publicitate Radio',
  'Print advertising': 'Publicitate tipărită',
  'TV advertising': 'Publicitate TV',
  'Stationery': 'Rechizite',
  'Recruiter': 'Recrutor',
  'Credit repair': 'Redresare Credit',
  'Public relations': 'Relații publice',
  'Truck repair': 'Reparatii camioane',
  'Machinery & Equipment repair': 'Reparatii masinarii & echipament',
  'Repairs (other)': 'Reparații (altele)',
  'Auto repair': 'Reparații auto',
  'Jewelry repair': 'Reparații bijuterii',
  'Computer repair': 'Reparații computer',
  'Appliance repair': 'Reparații electrocasnice',
  'Furniture/Upholstery repair': 'Reparații mobilă/tapițerie',
  'Pool, spa and sauna repair': 'Reparații piscine, spa și saun',
  'Data Protection Officer': 'Responsabil Protectia Datelor',
  'Restaurant': 'Restaurant',
  'Restorations': 'Restaurări',
  'Human resources': 'Resurse umane',
  'Retail (other)': 'Retail (altele)',
  'Clothing & Accessories retail': 'Retail haine & accesorii',
  'Drywall': 'Rigips',
  'Salon/Spa': 'Salon/Spa',
  'Mattresses': 'Saltele',
  'Health & Wellness (other)': 'Sănătate & Wellness (altele)',
  'Currency exchange': 'Schimb valutar',
  'Real estate tax exemptions': 'Scutiri taxe Imobiliare',
  'Secretarial': 'Secretariat',
  'Security (other)': 'Securitate (altele)',
  'Data security': 'Securitate date',
  'Employee safety': 'Securitatea angajaților',
  'Auto service': 'Service auto',
  'HOA services': 'Servicii ACP',
  'Administrative services': 'Servicii administrative',
  'Architectural services': 'Servicii arhitecturale',
  'Paving services': 'Servicii asfaltare',
  'Banking services': 'Servicii bancare',
  'Commercial banking': 'Servicii bancare comerciale',
  'Beverage services': 'Servicii băuturi',
  'Office services': 'Servicii birouri',
  'Cloud services': 'Servicii Cloud',
  'Accounting services': 'Servicii contabilitate',
  'Tree services': 'Servicii copaci',
  'Mobile bar services': 'Servicii de bar mobil',
  'Wildlife capture and relocation': 'Servicii de capturare și relocare animale sălbatice',
  'Waste collection services': 'Servicii de colectare a deșeurilor',
  'Medical concierge services': 'Servicii de concierge medical',
  'Lending services': 'Servicii de creditare',
  'Lighting services': 'Servicii de Iluminare',
  'CNC machining services': 'Servicii de prelucrare CNC',
  'Renovation services - Commercial': 'Servicii de renovare – Comercial',
  'Renovation services - Residential': 'Servicii de renovare – Rezidențial',
  'Cybersecurity services': 'Servicii de securitate cibernetică',
  'E-Commerce services': 'Servicii E-Commerce',
  'Education services': 'Servicii educație',
  'Energy services': 'Servicii energie',
  'Funeral services': 'Servicii funerare',
  'Government services': 'Servicii guvernamentale',
  'Health & Wellness services': 'Servicii Health & Wellness',
  'Real estate services (other)': 'Servicii imobiliare (altele)',
  'Internet services': 'Servicii internet',
  'Mortgage services': 'Servicii ipoteci, acte proprietate',
  'Legal services': 'Servicii juridice',
  'Online store services': 'Servicii magazin online',
  'Food services': 'Servicii mâncare',
  'Media services': 'Servicii Media',
  'Medical services': 'Servicii medicale',
  'Environmental services': 'Servicii mediu',
  'Shuttle/Limousine services': 'Servicii naveta/limuzine',
  'Landscaping services': 'Servicii peisagistică',
  'Personal services (other)': 'Servicii personale (altele)',
  'Payroll services': 'Servicii salarizare',
  'Printing services': 'Servicii tipărire',
  'Translation services': 'Servicii traduceri',
  'Freight transport services': 'Servicii transport bunuri',
  'Rainwater collection system': 'Sistem de colectare a apelor pluviale',
  'Water systems': 'Sisteme Apa',
  'GPS/Satellite navigation systems': 'Sisteme GPS / Navigație prin satelit',
  'Home cinema systems': 'Sisteme home cinema',
  'Security systems': 'Sisteme securitate',
  'Septic systems': 'Sisteme septice',
  'Social Media': 'Social Media',
  'Sophrologist': 'Sofrolog',
  'Computer software': 'Software calculatoare',
  'Solar': 'Solar',
  'Car wash/Cleaning': 'Spalatorie/Curatare masini',
  'Coworking space': 'Spațiu Coworking',
  'Laundry': 'Spălat',
  'Sports & Leisure (other)': 'Sport&Timp liber (altele)',
  'Glass': 'Sticlă',
  'Dentistry': 'Stomatologie',
  'Protective coatings/Sealants': 'Straturi protectoare/sigilatoare',
  'Temporary worker structures': 'Structuri temporare muncitori',
  'Supermarket': 'Supermarket',
  'Nutritional supplements': 'Suplimente nutriționale',
  'Surveyor': 'Supraveghetor',
  'Quantity surveyor': 'Supraveghetor cantitate',
  'Carpenter': 'Tamplar',
  'False ceiling/Suspended ceiling': 'Tavan fals / Tavan suspendat',
  'Technician - Audio, Video': 'Tehnician - Audio,Video',
  'Telecommunications (other)': 'Telecomunicații (altele)',
  'Mobile telecommunications': 'Telecomunicații mobile',
  'Plasterer': 'Tencuitor',
  'Massage therapist': 'Terapeut masaj',
  'Physical therapy': 'Terapeut recuperare fizică',
  'Wills/Trusts': 'Testamente/Fonduri',
  'Textiles': 'Textile',
  'Large format printing': 'Tipograf -  Format mare',
  'Digital printing': 'Tipograf - Digital',
  'Offset printing': 'Tipograf - Offset',
  'Document shredding': 'Tocarea hârtiei / documentelor',
  'Vehicle towing': 'Tractare vehicule',
  'Training & Coaching (other)': 'Training & Coaching (altele)',
  'IT Training': 'Training IT',
  'Online training': 'Training online',
  'Business training/Coaching': 'Training/Coach business',
  'Sales training/Coaching': 'Training/Coach Vanzari',
  'Property transfer': 'Transfer drept de proprietate',
  'Transport & Shipping (other)': 'Transport & Expeditii (altele)',
  'Commercial transport': 'Transport comercial',
  'Window treatment': 'Tratament Ferestre',
  'Mail services': 'Trimiteri poștă',
  'Tourism (other)': 'Turism (altele)',
  'Pipes': 'Țevi',
  'Essential oils': 'Uleiuri esențiale',
  'Uniforms': 'Uniforme',
  'UPS': 'UPS',
  'Garage doors': 'Usi garaj',
  'Construction materials sales': 'Vanzare materiale contructii',
  'Ticket sales': 'Vânzare bilete',
  'Book sales': 'Vânzare cărți',
  'Computer sales': 'Vânzare computer',
  'Used car sales': 'Vânzare de mașini second-hand',
  'Electronics sales': 'Vânzare electronice',
  'Furniture sales': 'Vânzare mobilă',
  'Commercial vehicle sales': 'Vânzare vehicule comerciale',
  'Auto sales': 'Vânzări auto',
  'Property sales': 'Vânzări de proprietăți',
  'Sports products sales': 'Vânzări produse sport',
  'Lighting systems sales': 'Vânzări sisteme iluminat',
  'Tire sales/installation': 'Vânzări/montaj anvelope',
  'Motor vehicles': 'Vehicule motorizate',
  'Veterinarian': 'Veterinar',
  'Wine/Wine suppliers': 'Vin/Furnizori vin',
  'Web Design': 'Web Design',
  'Web Development': 'Web Development',
}
